server:
  port: 8085

spring:
  application:
    name: order-service
  
  profiles:
    active: seed

  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}

  cache:
    type: redis
    redis:
      time-to-live: 60s
      cache-null-values: false

  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

  datasource:
    url: jdbc:postgresql://localhost:5432/order_db
    username: postgres
    password: 123456
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

services:
  cart:
    url: http://localhost:8084
  inventory:
    url: http://localhost:8087

realtime:
  redis:
    channel: ${REALTIME_REDIS_CHANNEL:novagear:realtime}

app:
  kafka:
    notification-topic: ${APP_KAFKA_NOTIFICATION_TOPIC:novagear.notifications}

features:
  kafka-notifications-enabled: ${FEATURES_KAFKA_NOTIFICATIONS_ENABLED:false}

logging:
  file:
    name: ${LOGGING_FILE_NAME:logs/order-service.log}
